backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:

  - name: "home"
    label: "Homepage"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/home/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Button Text", name: "button.label", widget: "string" }
          - { label: "Button Link", name: "button.url", widget: "string" }

      - label: "About Section"
        name: "about"
        file: "content/home/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team Members"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Avatar Image", name: "avatar", widget: "image" }

  - name: "publications"
    label: "Publications"
    folder: "content/publication"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list" }
      - { label: "Journal", name: "publication", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }